sample songs

paranoid = ddddddddddddddddccccccccfc..d...ddddddddddddddddccccccccfc..d...d......dcgj.dah....

axle off =

main = d...f..d.dg.d.c.d...a..d.d5.a.f.d.a.k.dc.c .e.d.......d...f..d.dg.d.c.d...a..d.d5.a.f.d.a.k.dc.c .e.d.......dc.a.f....d......h.hh.q.q.qi.g...h.hh.q.q.qi.....h.hh.q.q.qi.g...g.g.g.gh.h....
bridge (3x) = h.hh.q.q.qi.g...h.hh.q.q.qi.....h.hh.q.q.qi.g...
dc.a.f....d......

g.g.g.gh.h....


h.hh.q.q.qi.g...h.hh.q.q.qi.....h.hh.q.q.qi.g...g.g.g.gh.h....

full = d...f..d.dg.d.c.d...a..d.d5.a.f.d.a.k.dc.c .e.d.......d...f..d.dg.d.c.d...a..d.d5.a.f.d.a.k.dc.c .e.d.......dc.a.f....h.hh.q.q.qi.g...h.hh.q.q.qi.....h.hh.q.q.qi.g...g.g.g.gh.h....h.hh.q.q.qi.g...h.hh.q.q.qi.....h.hh.q.q.qi.g...g.g.g.gh.h....

the heat is on = .ceg3d.ceg3d....ceg3d.ceg3d.....ceg3d.ceg3d....ceg3d.ceg3d.k.k

.ceg3d.ceg3d.k.k
