sample songs

paranoid = ddddddddddddddddccccccccfc..d...ddddddddddddddddccccccccfc..d...d......dcgj.dah....

axle off = d...f..d.dg.d.c.d...a..d.d5.a.f.d.a.k.dc.c .e.d.......d...f..d.dg.d.c.d...a..d.d5.a.f.d.a.k.dc.c .e.d.......

